server:
  port: 8083
spring:
  profiles: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.132:3306/sso?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
feign:
  hystrix:
    enabled: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
#      defaultZone: http://47.111.232.105:8761/eureka #,http://localhost:8762/eureka
      defaultZone: http://test:123456@47.111.232.105:8761/eureka/